name: packtracker.io

on: [pull_request]

jobs:
  report:
    name: report webpack stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: report webpack stats
        uses: packtracker/report@2.3.0
        env:
          PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
